import Foundation

// MARK: - Dynamic Module Bootstrap

/// Auto-generated file. Registers all dynamically generated modules at app startup.
/// Re-generated by scripts/generate-module.py after each module creation.
/// DO NOT EDIT MANUALLY.
extension DynamicModuleRegistry {
    static func bootstrapAll() {
        registerBookTracker()
        registerCatCare()
        registerCoffeeTracker()
        registerCommuteLog()
        registerDailyAffirmations()
        registerDailyGratitude()
        registerDailySpending()
        registerGroceryList()
        registerHabitTracker()
        registerLearningTracker()
        registerMedicationTracker()
        registerMoodJournal()
        registerPeopleNotes()
        registerPlantWatering()
        registerPomodoroFocus()
        registerRecipeBook()
        registerScreenTimeGoal()
        registerSleepLog()
        registerSubscriptionTracker()
        registerWaterIntake()
    }
}
